version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@churrer.ch"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--accesslog=true"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy_net
    # Dynamic Configuration
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-router.rule=Host(`traefik.churrer.ch`)"
      - "traefik.http.routers.dashboard-router.service=api@internal"
      - "traefik.http.routers.dashboard-router.middlewares=dashboard-auth, dashboard-redirectscheme"
      - "traefik.http.routers.dashboard-router.entrypoints=websecure"
      - "traefik.http.routers.dashboard-router.tls=true"
      - "traefik.http.routers.dashboard-router.tls.certresolver=myresolver"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$2a$$12$$5rR.m1bZOeZdZYQyfpLJdObQHszwSE0j2FMNP..KUEJ44cs9ewLoC"
      - "traefik.http.middlewares.dashboard-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.dashboard-redirectscheme.redirectscheme.permanent=true"
networks:
  proxy_net:
    external: true
