version: '3.3'
services:
  visitor-frontend:
    container_name: visitor-frontend
    image: docker.registry.churrer.ch/churrers-visitor:1.6.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home.rule=Host(`churrer.ch`)"
      - "traefik.http.routers.home.middlewares=home-redirectscheme"
      - "traefik.http.routers.home.entrypoints=websecure"
      - "traefik.http.routers.home.tls=true"
      - "traefik.http.routers.home.tls.certresolver=myresolver"
      - "traefik.http.middlewares.home-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.home-redirectscheme.redirectscheme.permanent=true"
    networks:
      - proxy_net
networks:
  proxy_net:
    external: true